class Story:
    def __init__(self):
        # Level-based story texts narrated by David
        self.level_texts = {
            1: ["In Ethara’s lawless expanse, bandits prey on the vulnerable.",
                "An outpost rises, fueled by seeds—vessels of collateralized hope.",
                "Lock them in the lattice, commander, and mint your army’s dawn!"],
            2: ["Bandit raids scar the fields, testing the outpost’s resolve.",
                "Seeds hum with potential, channeling Ethereum’s pulse.",
                "Build wisely—every lock repays itself in time."],
            3: ["The bandits swarm, their greed insatiable.",
                "Walls buckle, but the Superseed lattice holds firm.",
                "Collateral grows—mint essence, defy the storm!"],
            4: ["Bandit blades clash against rising defenses.",
                "The outpost scales, an L2 atop Ether’s chain.",
                "Essence flows—self-repayment whispers of freedom."],
            5: ["The Bandit King looms, his crown forged of theft.",
                "Crush him with borrowed might—no interest, only victory.",
                "A bow-wielder joins—Superseed’s community stirs!"],
            6: ["Bandits fall, but zombies claw from shadowed graves.",
                "Lock seeds at fivefold strength—Supercollateral awakens!",
                "Debt shrinks as the lattice feeds on Ethara’s strife."],
            7: ["The zombie tide groans, relentless and ravenous.",
                "Archers loose volleys, born of minted essence.",
                "Revenue churns—SuperCDP repays the brave!"],
            8: ["Undead numbers choke the land, a rotting flood.",
                "The lattice hums, sequencer fees burning debt.",
                "Scale the outpost—towers rise on borrowed time!"],
            9: ["Zombies tighten their grip, decay evolving.",
                "Tanks rumble free, forged in Superseed’s vault.",
                "Proof of Repayment bids defiance into power!"],
            10: ["The zombie plague surges, Ethara’s brink.",
                "Shatter their core—debt fades with every blow.",
                "Superseed’s promise ignites—no lords, just us!"],
            11: ["Zombies rot away, but undead banners ascend.",
                "Ancient blades gleam, defying the living.",
                "Towers pierce the sky—Layer 2 scales anew!"],
            12: ["Undead axemen carve through the bold.",
                "SuperCDP mints essence, repaying its own.",
                "The community thrives—seeds drop from every foe!"],
            13: ["Mages hurl fire, arcane might unbound.",
                "The undead press, cold and unyielding.",
                "Walls stand tall—revenue burns debt to ash!"],
            14: ["Skeletal ranks flood the fields, endless.",
                "Volleys rain—Proof of Repayment fuels the fight.",
                "Superseed’s lattice turns despair to strength!"],
            15: ["A bone citadel looms—source of the undead.",
                "Break it, and Ethara breathes free.",
                "Debt vanishes—Superseed returns all to its kin!"],
            16: ["New undead lords rise, their power ancient.",
                "The outpost scales, an L2 of boundless reach.",
                "Collateral sings—self-repayment crowns the bold!"],
            17: ["Undead blades shimmer with lost magic.",
                "Tanks crush bone—essence mints unchecked.",
                "The lattice repays—no VC shadows here!"],
            18: ["Elite undead march, skill reborn in death.",
                "Supercollateral thrives, debt melting away.",
                "The citadel grows—Ethara’s heart beats onchain!"],
            19: ["Undead tighten their noose, unyielding.",
                "The lattice auctions defiance—PoR ignites!",
                "Towers stand firm—freedom scales with every seed!"],
            20: ["Undead elite surge, their might vast.",
                "The final clash nears—debt burns to nothing.",
                "Superseed’s vision shines—power to the people!"],
            21: ["Skeletal thrones tower, death’s dominion.",
                "Every seed locked repays itself in glory.",
                "The lattice hums—Ethara’s chains dissolve!"],
            22: ["Undead commanders rally, their end close.",
                "Strike true—revenue fuels the fall!",
                "Superseed’s mainnet lives—community reaps all!"],
            23: ["Bone legends defy the living, relentless.",
                "The outpost scales—Layer 2 unbreakable.",
                "No lords claim the gain—seeds repay the free!"],
            24: ["The undead muster their last, desperate stand.",
                "Ethara’s fate teeters—towers blaze bright.",
                "Supercollateral triumphs—debt fades to dust!"],
            25: ["The Undead King rises, crown of death agleam.",
                "Topple him—freedom’s mainnet dawns!",
                "Superseed reigns—self-repaying, unbound, ours!"]
        }

        # Additional event-based story texts
        self.event_texts = {
            "bandit_intro": ["Who dares trespass?",
                             "You’ll rue this day, fools!"],
            "bandit_surrender": ["Cease fire! Greater foes loom",
                                 "ahead—we must unite."],
            "surrender_part_two": ["Take these bows and arrows;",
                                   "they’ll serve you well."],
            "king_threat": ["Prepare to face my wrath!",
                            "None defy me and live!"],
            "end_story_victory": ["David with joy: Victory is ours!",
                                  "The enemy falls—Ethara stands tall!"],
            "tank_rescue": ["David: The tank is free!", "A stalwart defender joins us."],
        }

    def get_level_story(self, level_number):
        return self.level_texts.get(level_number, ["David: No story for this level yet."])

    def get_event_story(self, event_name):
        return self.event_texts.get(event_name, ["David: Something’s happening, but I’m not sure what…"])